window.env = {
  FIREBASE_API_KEY: "TU_API_KEY",
  FIREBASE_AUTH_DOMAIN: "TU_DOMINIO.firebaseapp.com",
  FIREBASE_PROJECT_ID: "TU_ID",
  FIREBASE_STORAGE_BUCKET: "TU_ID.appspot.com",
  FIREBASE_MESSAGING_SENDER_ID: "XXXXXX",
  FIREBASE_APP_ID: "1:XXXX:web:XXXX",
  FIREBASE_MEASUREMENT_ID: "G-XXXX"
};
mn